input:
  label: generate-1
  generate:
    mapping: root = {}
    interval: 1s
    count: 0
    batch_size: 1
    auto_replay_nacks: true
pipeline:
  processors:
    - label: log-1
      log:
        level: INFO
        fields_mapping: root = this
        message: ""
